import activityListRaw from './activityList.txt?raw'

const BASE_ACTIVITY_LABELS = {
  194: 'Show City Mcat Listing',
  388: 'Cross Domain Policy File On DIR',
  393: 'Show Mcat Page',
  394: 'Show Industry Page',
  396: 'Show Indian Exporters Page',
  398: 'Show Indian Services Page',
  399: 'Show How to Enable JavaScript Page',
  413: 'Show DIR Home Page',
  438: 'Viewed Product Details',
  506: 'Opened IndiaMART Home Page',
  507: 'Submitted Enquiry',
  511: 'Interaction Logged',
  513: 'Mobile Validation Checked',
  516: 'Opened Corporate Page',
  519: 'Opened Feedback Form',
  520: 'Opened Complaint Form',
  521: 'Opened Advanced Search Page',
  522: 'Opened Create Free Website Form',
  523: 'Opened Terms of Use Page',
  524: 'Opened Privacy Policy Page',
  525: 'Opened Link to Us Page',
  526: 'Opened FCP/MDC Enquiry Page',
  527: 'Opened FCP/MDC Page',
  530: 'Interaction Logged',
  531: 'Submitted Additional Enquiry Details',
  532: 'Opened FCP/MDC Page',
  533: 'Opened FCP/MDC Enquiry Page',
  592: 'Opened BI Overlay Form',
  593: 'Opened GI Include Page',
  658: 'Opened FCP/MDC Inside Page',
  673: 'System Fetched IndiaMART Cookies',
  674: 'System Resolved Location from IP',
  677: 'IndiaMART Search',
  678: 'System Resolved Country',
  752: 'Opened Search XML',
  753: 'Submitted Enquiry from Product Zoom',
  754: 'Submitted Enquiry from Distributor Form',
  755: 'Submitted Form while Creating Free Website',
  758: 'Downloaded Company PDF',
  759: 'Email Filled',
  816: 'Viewed EasyBuy Page',
  821: 'Opened Page',
  822: 'Opened Emerging Business Forum',
  866: 'Impcat Direct Request',
  867: 'Show DIR Home Page',
  868: 'CityWise Direct Request',
  869: 'Search Direct Request',
  849: 'Clicked Enquiry without JS Load',
  850: 'Clicked Ask Price without JS Load',
  854: 'Opened IndiaMART Homepage',
  856: 'Complaint Sent from IndiaMART',
  857: 'Clicked Enquiry without JS',
  858: 'Clicked Pay Now from IndiaMART',
  906: 'Opened Business Enquiry Form',
  907: 'Enquiry Submission Error Occurred',
  913: 'Show DIR Home Page',
  929: 'Submitted Enquiry from MDC Page',
  996: 'Submitted Enquiry from Product Zoom',
  997: 'Clicked On Satisfied With Search Results',
  1112: 'Clicked Ask Price Button',
  1128: 'Opened Seller Requests',
  1298: 'Marked FCP as Interested',
  1242: 'Save Details Of User when Clicked On Ask Current Price Once',
  1410: 'Interaction Logged',
  1350: 'Record User Interested',
  1489: 'Submitted Enquiry',
  1517: 'Clicked Ask Price',
  1594: 'Track the User',
  1526: 'Viewed App Download Ad',
  1527: 'Viewed BigBuyers Requirement',
  1528: 'Requested Seller Page',
  1653: 'Accessed Template',
  1649: 'Template Access Request',
  1654: 'Viewed Tolexo Banner',
  1655: 'Opened List Free Websites Page',
  1659: 'Opened Service Request Feedback Page',
  1752: 'Viewed Related MCAT Product on Tolexo',
  1753: 'Viewed FCP Recommendations',
  1754: 'Opened Related MCAT Catalog Link',
  1755: 'Opened BI Footer Form',
  1763: 'Generated OTP through Home Page',
  1764: 'System Loaded Recommendation Not Found Page',
  1775: 'On Scroll on Search Page',
  1773: 'Viewed Related Product Categories',
  1774: 'Viewed Popular Branded Categories',
  1782: 'Opened Industry Cluster Page',
  1785: 'Activity Identified',
  1840: 'Updated Seller Details',
  1841: 'System Fetched Product Detail for Sell on IndiaMART',
  1842: 'System Sent OTP',
  1843: 'Verified OTP via IndiaMART Seller',
  1844: 'System Auto-Fetched User Details',
  1861: 'Viewed Popular Branded Categories',
  1878: 'Opened BI Form',
  1883: 'To Fetch data on impcat page',
  1886: 'Login',
  1887: 'Logged In',
  1908: 'Clicked Next',
  1966: 'Started EasyBuy VOC Process',
  1975: 'System Encoded Mobile',
  1986: 'System Loaded Recently Viewed Section',
  1987: 'System Loaded Buyer Data',
  2004: 'impcat internal activity',
  2005: 'Triggered PayX External Activity',
  2006: 'Performed FCP/MDC Search Activity',
  2032: 'Added Product in Step 3',
  2039: 'City Filter',
  2040: 'Open Search Request',
  2041: 'Started New User Onboarding',
  2064: 'System Wrote Data to File',
  2075: 'SID Product Pages',
  2100: 'Standard Product Pages',
  2073: 'Opened Big Brands Page',
  2113: 'Clicked HL Mailer from Homepage',
  2114: 'Requested Callback via HL Mailer',
  2115: 'Initiated Payment via HL Mailer',
  2116: 'Selected Monthly Plan via HL Mailer',
  2117: 'Selected Annual Plan via HL Mailer',
  2118: 'Selected Yearly INR Plan via HL Mailer',
  2156: 'Submitted Basic Information Form',
  2157: 'Filled Business Details',
  2158: 'Submitted GST Details',
  2210: 'City Directory Page',
  2215: 'Internal System Request Triggered',
  2238: 'Robots Text File',
  2239: 'Browser Configuration',
  2303: 'Internal Request',
  2242: 'Viewed Latest Products',
  2604: 'System Displayed Recommended Data',
  2605: 'Explored Covid-19 Medical Supplies',
  2606: 'Viewed Covid-19 Supplies',
  2633: 'Internal System Request Triggered',
  2652: 'Created New Seller Account',
  2653: 'Submitted Seller GST Details',
  2654: 'Re-submitted Seller GST Details',
  2655: 'Saved Onboarding Disposition',
  2656: 'System Fetched State from Pincode',
  2657: 'System Fetched GST Disposition',
  2658: 'Seller Email Verified',
  2659: 'Seller Mobile Verified',
  4034: 'IndiaMART Search PWA Requests for Page',
  4035: 'Video req on Search',
  4036: 'Standard products req on Search',
  4096: 'ISQ on Search',
  4121: 'Recommended Seller Displayed',
  4122: 'E-commerce PLA Feed Displayed',
  4123: 'Viewed Ratings and Reviews',
  4242: 'Call Intent',
  4243: 'Enquiry Intent',
  4244: 'Price Enquiry',
  4245: 'Product Price Enquiry',
  4246: 'Ask Price Enquiry',
  4247: 'Products Viewed',
  4248: 'Company Viewed',
  4249: 'Images Viewed',
  4250: 'Product Enquiry',
  4251: 'Contact Intent',
  4252: 'Intent to Call',
  4253: 'Viewed Products',
  4254: 'Intent for Enquiry',
  4255: 'Price Info Required',
  4256: 'Quotes Required',
  4257: 'Viewed Product Image',
  4258: 'Viewed Company',
  4269: 'Initiated Price Enquiry',
  4270: 'Triggered Call Intent',
  4271: 'Viewed Product Listing',
  4272: 'Viewed Company Profile',
  4273: 'Clicked Ask Price Button',
  4383: 'Viewed Product Details (SPA)',
  4391: 'PWA search page next',
  4392: 'On Scroll on Search Page-Next-old',
  4396: 'Product Name Displayed',
  4397: 'Company Name Displayed',
  4410: 'BL form Step 1',
  4411: 'BL form Step 2',
  4412: 'BL form Final Step',
  4398: 'Completed BL Form Step 1',
  4399: 'Completed BL Form Step 2',
  4400: 'Completed BL Form Final Step',
  4401: 'Completed BL Form Step 1',
  4402: 'Completed BL Form Step 2',
  4403: 'Completed BL Form Final Step',
  4404: 'Completed BL Form Step 1',
  4405: 'Completed BL Form Step 2',
  4406: 'Completed BL Form Final Step',
  4407: 'Completed BL Form Step 1',
  4408: 'Completed BL Form Step 2',
  4409: 'Completed BL Form Final Step',
  4425: 'Clicked Contact Supplier CTA',
  4426: 'Clicked MDC Image CTA',
  4427: 'Clicked FCP Image CTA',
  4428: 'Clicked MDC Product CTA',
  4429: 'Clicked FCP Product CTA',
  4430: 'Clicked MDC Price CTA',
  4431: 'Clicked FCP Price CTA',
  4432: 'Clicked MDC Company CTA',
  4433: 'Clicked FCP Company CTA',
  4434: 'Clicked MDC View All CTA',
  4435: 'Clicked FCP View All CTA',
  4436: 'Clicked MDC View More Details CTA',
  4437: 'Clicked FCP View More Details CTA',
  4445: 'Clicked TDWIM Image CTA',
  4446: 'Clicked TDWIM Product CTA',
  4447: 'Clicked TDWIM Price CTA',
  4448: 'Clicked TDWIM Company CTA',
  4449: 'Clicked TDWIM View All CTA',
  4450: 'Clicked TDWIM View More Details CTA',
  4479: 'User opened Export homepage',
  4480: 'User searched on Export search page',
  4481: 'User viewed Export product details page',
  4602: 'User viewed Export company products',
  4629: 'youtube video section ajax call (mcat city pages)',
  4630: 'ecom product reccomendations section ajax call',
  4631: 'related category new user city section ajax call',
  4632: 'SEARCH PAGE API',
  4633: 'SEARCH PAGE API',
  4634: 'reauth api ajax call from client side',
  4635: 'homepage ajax request',
  4636: 'Session detail API',
  4656: 'Internal enquiry request triggered (BL flow)',
  4657: 'Viewed Product Detail Page',
  4729: 'Internal enquiry request triggered (BL flow)',
  4730: 'User opened Export Get Quote page',
  4731: 'User visited Export Trust page',
  4732: 'User explored Export country page',
  4733: 'User browsed Export industry page',
}

const parseActivityLabels = (rawText) => {
  return String(rawText || '')
    .split('\n')
    .reduce((labels, line) => {
      const trimmed = line.trim()
      if (!trimmed) {
        return labels
      }

      const match = trimmed.match(/^(\d+)\s*:\s*(.+)$/)
      if (!match) {
        return labels
      }

      const activityId = Number(match[1])
      if (!Number.isFinite(activityId)) {
        return labels
      }

      labels[activityId] = match[2].trim()
      return labels
    }, {})
}

const ACTIVITY_LIST_LABELS = parseActivityLabels(activityListRaw)

export const ACTIVITY_LABELS = {
  ...BASE_ACTIVITY_LABELS,
  ...ACTIVITY_LIST_LABELS,
}

